### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Raydelta** [VivaPayments/API#2160]
Hey, using your lastest woocommerce smart checkout plugin + latest woocommerce & saw this in the error logs today:

[05/04/2022:18:05:35 +0100] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /var/www/html/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php:322\nStack trace:\n#0 /var/www/html/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php(444): WC_VIVAWALLET->generate_form(140095)\n#1 /var/www/html/wp-includes/class-wp-hook.php(307): WC_VIVAWALLET->receipt_page(140095)\n#2 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)\n#3 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)\n#4 /var/www/html/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action('woocommerce_rec...', 140095)\n#5 /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/var/www/html/w...')\n#6 /var/www/html/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(208): wc_get_template('checkout/order-...', Array)\n#7 /var/www/html/wp-con 

Should I be worried?

**Comment by can3ry** [comment]
Hi @Raydelta 
Thanks for the query.
Our smart checkout plugin works without error logs with the latest version of WooCommerce(v6.3.1). However, it is possible our plugin is not compatible with the specific theme or plugins you're using. Is there any way of changing the theme and disabling the plugins temporarily, and testing our payment plugin again after that? Please let us know if you still see an error log. 
Thanks
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hi again @Raydelta 
Could you also let us know if you see the successful transactions on your dashboard? How is the payment process going on on the front end? Do you see any errors or unusual things?
Thanks
Viva Wallet Development Team

**Comment by Raydelta** [comment]
Heya,

Dont get me wrong, the payments work, we did £2170 in sales yesterday and £1684 so far today (1pm local time) and 92k last month. However I saw this in our Server logs, server side error logs with Krystal Onyx.

So I wish to know what the error means and why it happened.

**Comment by Raydelta** [comment]
I moved to Woocommerce V6.3.1 on Early hours tuesday Morning. Then I spotted this error in the error logs dated 05/04/22 18:05

Using Astra Theme. No prior issues last month when on Woo 6.0

**Comment by can3ry** [comment]
Hello @Raydelta  
I've tested the same theme on my local and it did not throw an error but I would like to check more.
Could you please send your merchant id and the website to **cyazici@vivawallet.com**?
Thanks

**Comment by Raydelta** [comment]
Will do. Found afew other errors in server error logs, no complaints from customers but wanna work out what it is

**Comment by can3ry** [comment]
Hi @Raydelta 
I am closing this ticket for now.
Please feel free to send details to my email shared above. 
Thanks

**Comment by Raydelta** [comment]
Ive emailed you with quite abit of detail but had no reply.

**Comment by can3ry** [comment]
Hi @Raydelta 
I just noticed that it went to my junk folder. Apologize for this. 
Let me check and get back to you.
Thanks
Viva Wallet Development Team
