### ISSUE TITLE
When doing transactions using VW POS Demo, no transaction found on it

### ISSUE THREAD

**Issue by adoyen** [VivaPayments/API#2357]
Hello,

Following issue #2356 , I did some transactions using VW POS Demo.
- Some using card presentation (tap on phone), transactions coming from my application, ISV account
- Some using QR code (vivawallet) given by VW POS Demo, transactions coming from my application, ISV account
- Some directly on the terminal (encoding amount and confirming presenting card using tap on phone). No link with my application.

All successful.

In page "Transactions" on VW POS Demo, I cannot see any transactions. It says empty summary.
(Filters selecting All types, All states and any period of time)

So, I assume that if I cannot use refund from session (https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Make-Transactions/paths/~1ecr~1isv~1v1~1transactions:refund/post),
it is because no transaction found:

See call below
```
Call with {
  "headers": {
    "Authorization": "Bearer xxx" // ISV Token
  },
  "data": {
    "sessionId": "a6WFu3WFKs5Prvw6E-3SM8nDLPcEDeRNSCc-refund",
    "terminalId": "16001754",
    "cashRegisterId": "ClubOnline",
    "parentSessionId": "a6WFu3WFKs5Prvw6E-3SM8nDLPcEDeRNSCc",
    "amount": 400,
    "currencyCode": "978",
    "merchantReference": "a6WFu3WFKs5Prvw6E",
    "customerTrns": "ClubOnline transaction Club de basket - refund a6WFu3WFKs5Prvw6E",
    "isvDetails": {
      "terminalMerchantId": "a580b930-5e41-421b-8914-2c9fa30eec66"
    }
  }
}
Response err: Error: failed [404] {"detail":"Not Found"}
    at makeErrorByStatus (packages/jkuester:http/httpcall_common.js:17:10)
    at packages/jkuester:http/httpcall_server.js:159:23
    at /Users/arnaud/.meteor/packages/t++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/
  response: {
    statusCode: 404,
    content: '{"detail":"Not Found"}',
    headers: {
      connection: 'close',
      'content-length': '22',
      'content-type': 'application/json',
      date: 'Thu, 23 Mar 2023 09:24:53 GMT',
      server: 'uvicorn',
      'set-cookie': 'ak_bmsc=636FC11222C49AB26E78214F396FFA32~000000000000000000000000000000OHpPCRf5H+OZPxfEUoeE5a5Lsd9ayiyvTNuLKPPAgYz45grJVCGTCG9k/xvWg5deUtRxcJnDi2jaUX8SB7T/7uS2izPNDIwFccEb7GSdxRZDZxUenFaoJZZb4mGivzxZV2EFEFq7nJ2DKWKIpcF2RIkm8illsvXRpLoI5hC5hzk/DAQ0H76LWPKxOZAxLZ1jVjrp//GYj7jcDpQ6D/DWKTtpfepzwH/dmD3CLEkP52WD1iByX7/d3nkbz1W//x0Mke/1ykenwfvyX6i4w/rPw23o=; Domain=.vivapayments.com; Path=/; Expires=Thu, 23 Age=7200; Secure; HttpOnly',
      'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
      'x-process-time': '0.0005192756652832031',
      'x-viva-correlationid': '23-082-A11D350281E5'
    },
    ok: false,
    redirected: undefined,
    data: { detail: 'Not Found' }
  }
}
```

Furthermore, concerning operation 
https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Cancel-Transactions/paths/~1api~1transactions~1{transactionid}/delete
Would it be possible to use also ISV token oauth2 like nearly all other API instead of a specific authentication with unknown credentials we need to ask to you ?

Thanks !

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you very much for contacting us. Can you please send us the [Initiate Sales request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Make-Transactions/paths/~1ecr~1isv~1v1~1transactions:sale/post) for the transaction? About the empty transactions list issue, we would like to inform you that we are investigating it. 

Lastly, our [Cancel Transaction API request](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Cancel-Transactions/paths/~1api~1transactions~1{transactionid}/delete) requires credentials that we can only provide. We kindly suggest you to contact us via live chat to send you those credentials.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Hello,
I don't have anymore the initial sales request. I could give you another one if necessary, but I think that firstly fix the issue about empty transactions list will do the trick.

I asked the credentials to support@vivawallet.com, but they don't seem to know what it is. They will probably ask you about that.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for your swift response.  
Yes, please send us another one. Also, send us the Refund a Transaction request.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Hello,
Sorry for late reply, I was very busy lastly.

Creating terminal session:
```
{
  "headers": {
    "Authorization": "Bearer xxx"
  },
  "data": {
    "sessionId": "ELguxsTQSjdKALRiw-KfoigRzvcgM46fb9f",
    "terminalId": "16001754",
    "cashRegisterId": "ClubOnline",
    "amount": 229.99999999999997,
    "currencyCode": "978",
    "merchantReference": "ELguxsTQSjdKALRiw",
    "customerTrns": "ClubOnline transaction Club de basket - ELguxsTQSjdKALRiw",
    "maxInstalments": 0,
    "tipAmount": 0,
    "isvDetails": {
      "amount": 2,
      "terminalMerchantId": "a580b930-5e41-421b-8914-2c9fa30eec66"
    }
  }
}
Response: {
  statusCode: 200,
  content: '',
  headers: {
    connection: 'close',
    'content-length': '0',
    date: 'Tue, 28 Mar 2023 06:26:03 GMT',
    server: 'uvicorn',
    'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
    'x-process-time': '0.6449775695800781',
    'x-viva-correlationid': '23-087-92744EDD671B'
  },
  ok: true,
  redirected: undefined,
  data: null
}
```

Payment done by card presented, webhook received:
```
{
  Url: 'http://doyendor.be/webhook/transaction/vivawallet/6EgYi5XfdmC3vrK8F',
  EventData: {
    Moto: false,
    BinId: 42,
    Ucaf: null,
    Email: null,
    Phone: null,
    BankId: 'NET_MASTER',
    Systemic: false,
    Switching: false,
    ParentId: null,
    Amount: 2.29,
    ChannelId: '09913a34-c7d2-4e99-a3a7-550f2063d3b1',
    TerminalId: 16001754,
    MerchantId: 'a580b930-5e41-421b-8914-2c9fa30eec66',
    OrderCode: 3087082979001754,
    ProductId: null,
    StatusId: 'F',
    FullName: null,
    ResellerId: 'e9afd2a1-4e28-415f-8e65-8f668b36d8f9',
    DualMessage: false,
    InsDate: '2023-03-28T09:26:22.447',
    TotalFee: 0,
    CardToken: '238F19C796FBD3E3889EAD976EBF9CCBCA35C3C7',
    CardNumber: '511580XXXXXX6241',
    TipAmount: 0,
    SourceCode: '6157',
    SourceName: 'demo',
    Latitude: 50.711546,
    Longitude: 4.993459,
    CompanyName: 'xxx',
    TransactionId: '0418de5f-f31d-494a-b31a-42fa671a4098',
    CompanyTitle: 'Doyen Arnaud',
    PanEntryMode: '07',
    ReferenceNumber: 203436,
    ResponseCode: '00',
    CurrencyCode: '978',
    OrderCulture: 'fr-FR',
    MerchantTrns: 'ELguxsTQSjdKALRiw',
    CustomerTrns: 'ClubOnline transaction Club de basket - ELguxsTQSjdKALRiw',
    IsManualRefund: false,
    TargetPersonId: null,
    TargetWalletId: null,
    AcquirerApproved: false,
    LoyaltyTriggered: false,
    TransactionTypeId: 5,
    AuthorizationId: '203436',
    TotalInstallments: 0,
    CardCountryCode: 'BE',
    CardIssuingBank: 'Bunq B.v.',
    RedeemedAmount: 0,
    ClearanceDate: null,
    CurrentInstallment: 0,
    Tags: [],
    BillId: null,
    ConnectedAccountId: null,
    ResellerSourceCode: 'Default',
    ResellerSourceName: 'Default',
    ResellerCompanyName: 'xxx',
    CardUniqueReference: '238F19C796FBD3E3889EAD976EBF9CCBCA35C3C7',
    ResellerSourceAddress: null,
    CardExpirationDate: '2023-12-31T00:00:00',
    RetrievalReferenceNumber: '308706203436',
    AssignedMerchantUsers: [ '3c5dd92f-830b-4c32-8942-7c4f8b4479b1' ],
    AssignedResellerUsers: [],
    CardTypeId: 1,
    ResponseEventId: null,
    ElectronicCommerceIndicator: null,
    OrderServiceId: 0,
    DigitalWalletId: null
  },
  Created: '2023-03-28T06:26:22.515994Z',
  CorrelationId: '23-087-476451FC',
  EventTypeId: 1796,
  Delay: null,
  MessageId: '966d3558-80bb-439b-87a6-e30327a329ec',
  RecipientId: 'a580b930-5e41-421b-8914-2c9fa30eec66',
  MessageTypeId: 512
}
```

My app, when receiving the webhook ask for session status (which is still under processing):
```
Call with https://demo-api.vivapayments.com/ecr/isv/v1/sessions/gM46fb9f {
  "headers": {
    "Authorization": "Bearer xxx"
  }
}
Response: {
  statusCode: 202,
  content: '{"detail":"The session is being processed"}',
  headers: {
    connection: 'close',
    'content-length': '43',
    'content-type': 'application/json',
    date: 'Tue, 28 Mar 2023 06:26:23 GMT',
    server: 'uvicorn',
    'set-cookie': 'ak_bmsc=xxx; Domain=.vivapayments.com; Path=/; Expires=Tue, 28 Mar 2023  Secure; HttpOnly',
    'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
    'x-process-time': '0.14283537864685059',
    'x-viva-correlationid': '23-087-16DB2B1A9BA5'
  },
  ok: true,
  redirected: undefined,
  data: { detail: 'The session is being processed' }
}
```

So then, it tries to retrieve transaction:
```
Call with https://demo-api.vivapayments.com/checkout/v2/isv/transactions/a671a4098 {
  "headers": {
    "Authorization": "Bearer xxx"
  },
  "params": {
    "merchantId": "a580b930-5e41-421b-8914-2c9fa30eec66"
  }
}
Response: {
  statusCode: 200,
  content: '{"email":null,"amount":2.29,"orderCode":3087082979001754,"statusId":"F","fullNa-28T09:26:22.447+03:00","cardNumber":"511580XXXXXX6241","currencyCode":"978","customerTrns"ub de basket - ELguxsTQSjdKALRiw","merchantTrns":"ELguxsTQSjdKALRiw","transactionTypeId":5,otalInstallments":0,"cardCountryCode":"BE","cardIssuingBank":"Bunq B.v.","currentInstallmen"238F19C796FBD3E3889EAD976EBF9CCBCA35C3C7","cardTypeId":1,"digitalWalletId":null}',
  headers: {
    connection: 'close',
    'content-length': '541',
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 28 Mar 2023 06:26:23 GMT',
    prx: '03',
    'set-cookie': 'ak_bmsc=xxx; Domain=.vivapayments.com; Path=/; Expires=Tue, 28 Mar 2023  Secure; HttpOnly',
    'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
    'x-viva-correlationid': '23-087-D2FC71D8',
    'x-viva-eventid': '0'
  },
  ok: true,
  redirected: undefined,
  data: {
    email: null,
    amount: 2.29,
    orderCode: 3087082979001754,
    statusId: 'F',
    fullName: null,
    insDate: '2023-03-28T09:26:22.447+03:00',
    cardNumber: '511580XXXXXX6241',
    currencyCode: '978',
    customerTrns: 'ClubOnline transaction Club de basket - ELguxsTQSjdKALRiw',
    merchantTrns: 'ELguxsTQSjdKALRiw',
    transactionTypeId: 5,
    recurringSupport: false,
    totalInstallments: 0,
    cardCountryCode: 'BE',
    cardIssuingBank: 'Bunq B.v.',
    currentInstallment: 0,
    cardUniqueReference: '238F19C796FBD3E3889EAD976EBF9CCBCA35C3C7',
    cardTypeId: 1,
    digitalWalletId: null
  }
}
```

After that, I try to ask for a refund using [Refund a transaction (terminal)](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Make-Transactions/paths/~1ecr~1isv~1v1~1transactions:refund/post) :
```
{
  "headers": {
    "Authorization": "Bearer xxx"
  },
  "data": {
    "sessionId": "ELguxsTQSjdKALRiw-KfoigRzvcgM46fb9f-refund",
    "terminalId": "16001754",
    "cashRegisterId": "ClubOnline",
    "parentSessionId": "ELguxsTQSjdKALRiw-KfoigRzvcgM46fb9f",
    "amount": 229.99999999999997,
    "currencyCode": "978",
    "merchantReference": "ELguxsTQSjdKALRiw",
    "customerTrns": "ClubOnline transaction Club de basket - refund ELguxsTQSjdKALRiw",
    "isvDetails": {
      "terminalMerchantId": "a580b930-5e41-421b-8914-2c9fa30eec66"
    }
  }
}
Response err: Error: failed [404] {"detail":"Not Found"}
    at makeErrorByStatus (packages/jkuester:http/httpcall_common.js:17:10)
    at packages/jkuester:http/httpcall_server.js:159:23
    at /Users/arnaud/.meteor/packages/t++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/
  response: {
    statusCode: 404,
    content: '{"detail":"Not Found"}',
    headers: {
      connection: 'close',
      'content-length': '22',
      'content-type': 'application/json',
      date: 'Tue, 28 Mar 2023 06:26:43 GMT',
      server: 'uvicorn',
      'set-cookie': 'ak_bmsc=xxx; Domain=.vivapayments.com; Path=/; Expires=Tue, 28 Mar 7200; Secure; HttpOnly',
      'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
      'x-process-time': '0.002027273178100586',
      'x-viva-correlationid': '23-087-86131D8C23C7'
    },
    ok: false,
    redirected: undefined,
    data: { detail: 'Not Found' }
  }
}
```

And indeed, it's not found since there is nothing in the transactions list on the VW POS Demo application.

Best regards

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for the information. We will review your API requests and we will inform you shortly.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for waiting. Kindly note that in our demo environment you can refund a transaction only via the merchant's account (API request using merchant's credentials or Viva Wallet UI). If you wish to refund a transaction via your ISV account, this feature is only available in our live environment. This feature will be available soon in our demo environment. We are also working on the issue of the empty transactions list in our POS devices that are attached to a demo account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for waiting. The issue of the empty transactions list has been resolved. 
If you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
