### ISSUE TITLE
Problem with Magento 2.x in Callback.php Controller

### ISSUE THREAD

**Issue by JKouvakis** [VivaPayments/API#451]
in 	protected function paymentAction()
after the curl execution the object returns no transaction/amount/status etc information

`					$TransactionId = $t->TransactionId;
					$Amount = $t->Amount;
					$StatusId = $t->StatusId;
					$CustomerTrns = $t->CustomerTrns ;
                    $message = "Transactions completed Successfully";
                    $update_order->setOrderState('paid')->save();
`
i've printed out the curl url and it is correct 
`https://www.vivapayments.com/api/transactions/?ordercode=XXXXXXXXX`

also the $StatusId is not predefined as variable as also the $txtMsg resulting in error code in magento if it cant find the response object

**Comment by VivaWalletSupport** [comment]
Unfortunately I am not able to replicate the problem simulating a success transaction in the demo environment, also there is no $txtMsg variable in the controller file.

**Comment by JKouvakis** [comment]
`		else
		{
			$this->_createVivaPaymentsComment($message);
            $this->_order->cancel()->save();
			$this->messageManager->addError("<strong>Error:</strong> $txMsg <br/>");
			$redirectUrl = $this->_paymentMethod->getCancelUrl();
			$this->_redirect($redirectUrl);
		}		
`
line 142 addError("<strong>Error:</strong> $txMsg <br/>")

the account is ready from viva and not in pending status... so what can I do to debug the process?

**Comment by VivaWalletSupport** [comment]
The $txMsg variable exists and is located in the fail routine, I corrected it in $message. I would suggest to setup and test in the demo mode first and to use a sufficient transaction amount.

**Comment by JKouvakis** [comment]
in demo mode i get


`{"0":"Notice: Trying to get property of non-object in \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/app\/code\/Ced\/VivaPayments\/Model\/PaymentMethod.php on line 165","1":"#0 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/app\/code\/Ced\/VivaPayments\/Model\/PaymentMethod.php(165): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Trying to get p...', '\/var\/www\/vhosts...', 165, Array)\n#1 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/generated\/code\/Ced\/VivaPayments\/Model\/PaymentMethod\/Interceptor.php(37): Ced\\VivaPayments\\Model\\PaymentMethod->getPostHTML(Object(Magento\\Sales\\Model\\Order\\Interceptor), NULL)\n#2 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/app\/code\/Ced\/VivaPayments\/Controller\/Checkout\/Start.php(40): Ced\\VivaPayments\\Model\\PaymentMethod\\Interceptor->getPostHTML(Object(Magento\\Sales\\Model\\Order\\Interceptor))\n#3 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/generated\/code\/Ced\/VivaPayments\/Controller\/Checkout\/Start\/Interceptor.php(24): Ced\\VivaPayments\\Controller\\Checkout\\Start->execute()\n#4 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->execute()\n#5 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->___callParent('dispatch', Array)\n#7 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/generated\/code\/Ced\/VivaPayments\/Controller\/Checkout\/Start\/Interceptor.php(39): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->___callPlugins('dispatch', Array, Array)\n#9 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/App\/FrontController.php(55): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#12 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#14 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#16 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#18 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#19 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#20 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#21 \/var\/www\/vhosts\/islandboutique.gr\/httpdocs\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#22 {main}","url":"\/vivapayments\/checkout\/start","script_name":"\/index.php"}`

**Comment by VivaWalletSupport** [comment]
Could you post some screenshots from your extension settings? Obscure the API Key.

**Comment by JKouvakis** [comment]
![download](https://user-images.githubusercontent.com/16337269/35149597-5e9cfdb0-fd1f-11e7-9337-6315f9174153.png)

**Comment by VivaWalletSupport** [comment]
Can you confirm that the used merchantid, apikey and source code are from your demo account?

**Comment by JKouvakis** [comment]
yes... all are same in magento admin and viva profile...

**Comment by VivaWalletSupport** [comment]
To be sure on this, you are using the credentials from your Viva **demo account** and not from your Live account
